### ISSUE TITLE
How to get my team on my onshape?

### ISSUE THREAD

**Issue by johnalleO** [Max5254/onshape4frc.com#7]
I am trying to get all of my team on onshape so that we can collaborate and work on our robot together. I cannot find anywhere that this is discussed and cannot find out how to go about this. Any help would be appreciated. Thank you, John A. O'Brien Team Tesla 4998.

**Comment by JTerv** [comment]
@johnalleO Hey John,

Sorry about the large delay in response - it seems that neither of us were notified of your message, so I'm seeing it for the first time just now.

Are you still having trouble getting Onshape setup for your team, or were you all able to figure it out? Let us know and we can point you in the correct direction if needed!
